### PR TITLE
Fix building due to fall through warning

### LINKED ISSUE #51: FTBFS visit_all_subdirs fallthrough
**Describe the bug**
```
tumbleweed-pkg/t/s/src (main)$ make CC=gcc
gcc -std=c11 -c -Wall -Wextra -Werror -O3 -flto -fno-asynchronous-unwind-tables -fno-unwind-tables -I/usr/include/json-c  -I/usr/include/python3.11 -I/usr/include/python3.11 -DUSE_PYTHON -MT alsa.o -MMD -MP -MF ./alsa.Td -o alsa.o alsa.c
mv -f ./alsa.Td ./alsa.d && touch alsa.o
gcc -std=c11 -c -Wall -Wextra -Werror -O3 -flto -fno-asynchronous-unwind-tables -fno-unwind-tables -I/usr/include/json-c  -I/usr/include/python3.11 -I/usr/include/python3.11 -DUSE_PYTHON -MT poller.o -MMD -MP -MF ./poller.Td -o poller.o poller.c
mv -f ./poller.Td ./poller.d && touch poller.o
gcc -std=c11 -c -Wall -Wextra -Werror -O3 -flto -fno-asynchronous-unwind-tables -fno-unwind-tables -I/usr/include/json-c  -I/usr/include/python3.11 -I/usr/include/python3.11 -DUSE_PYTHON -MT process_configuration.o -MMD -MP -MF ./process_configuration.Td -o process_configuration.o process_configuration.c
mv -f ./process_configuration.Td ./process_configuration.d && touch process_configuration.o
gcc -std=c11 -c -Wall -Wextra -Werror -O3 -flto -fno-asynchronous-unwind-tables -fno-unwind-tables -I/usr/include/json-c  -I/usr/include/python3.11 -I/usr/include/python3.11 -DUSE_PYTHON -MT utility.o -MMD -MP -MF ./utility.Td -o utility.o utility.c
utility.c: In function ‘visit_all_subdirs’:
utility.c:328:20: error: this statement may fall through [-Werror=implicit-fallthrough=]
  328 |                 if (!isdir(path, path_fd, ent->d_name))
      |                    ^
utility.c:331:13: note: here
  331 |             case DT_DIR:
      |             ^~~~
cc1: all warnings being treated as errors
make: *** [Makefile:76: utility.o] Error 1
tumbleweed-pkg/t/s/src (main)$
```

**Expected behaviour**
Clear build

**Actual behaviour**
Fails to build

**Desktop (please complete the following information):**
 - The Linux flavour you use: openSUSE/Tumbleweed
 - `swaystatus` version: master version from git
 - `swaystatus` configuration none

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #51

### CODE REVIEW

**Comment by NobodyXu** [comment]
@mcepl Can u try this PR please?

**Comment by mcepl** [comment]
That feels like a cowardly way how to do it. I believe, [I did better](https://git.sr.ht/~mcepl/swaystatus/commit/4ab4d3f69b837602153ae4431a9b9a0f7402de17#src/utility.c).

**Comment by NobodyXu** [comment]
> That feels like a cowardly way how to do it. I believe, [I did better](https://git.sr.ht/~mcepl/swaystatus/commit/4ab4d3f69b837602153ae4431a9b9a0f7402de17#src/utility.c).

Yeah that's indeed a better solution!

Would you mind putting up a PR?

**Comment by mcepl** [comment]
> > That feels like a cowardly way how to do it. I believe, [I did better](https://git.sr.ht/~mcepl/swaystatus/commit/4ab4d3f69b837602153ae4431a9b9a0f7402de17#src/utility.c).
> 
> Yeah that's indeed a better solution!
> 
> Would you mind putting up a PR?

You mean like Linus intended?

```
The following changes since commit 18d131631ac25a92a78630e033e89d751ebe3306:

  Fix comparison of int of diff sign in MemoryUsagePrinter.cc:92 (2021-09-12 14:38:21 +1000)

are available in the Git repository at:

  https://git.sr.ht/~mcepl/swaystatus 

for you to fetch changes up to 51394b59952ff7a930fd5f5e3a0a518973b77740:

  Properly mark a branch of case statement as fallthrough. (2023-12-21 16:27:31 +0100)

----------------------------------------------------------------
Matěj Cepl (1):
      Properly mark a branch of case statement as fallthrough.

 src/utility.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/utility.c b/src/utility.c
index 8f949e6..695fe1a 100644
--- a/src/utility.c
+++ b/src/utility.c
@@ -327,6 +327,7 @@ void visit_all_subdirs(const char *path, subdir_visiter visiter, ...)
                 // Check if it is a dir after resolution
                 if (!isdir(path, path_fd, ent->d_name))
                     break;
+                [[fallthrough]];
 
             case DT_DIR:
                 if (strcmp(ent->d_name, ".") != 0 && strcmp(ent->d_name, "..") != 0)
```

**Comment by NobodyXu** [comment]
Nah I was referring to a Pull Request on GitHub.

But if you are don't want to do that, I can open a Pull Request on GitHub for you with you as the co-author.

**Comment by NobodyXu** [comment]
@mcepl Thanks, I've opened #53 which adopts your suggestion.

**Pull request closed without merging**
